# Pezhman Khorasani, Xiaoyi Ling, Tiffany Luu
# Makefile for GPIO User Space, music.c program
# CSE/EE 474 Lab 1
# 4/7/2017

# default target:
music: music.c
	gcc -o music music.c

# phony target for clean command
.PHONY: clean

# removes all object files, executables, and editor files
clean:
	rm -f *.o *~ music

